version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-task-stack-2"
s3_bucket = "logstorage"
s3_prefix = "aws-task-stack-2"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
