name: AWS Task lambda
on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # Build using SAM
      - run: sam build -t ../.aws-sam/build/template.yaml
      # Deploy on AWS
      - run: dotnet lambda deploy-function stack-logprocessorlambda      

